#!/usr/bin/env bash
# Transfering a File to Webserver
# $1 = the File Path
# $2 = the Webserver's IP address
# $3 = Username
# $4 = the SSH public key location
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
