#!/usr/bin/env bash
# This Script Generates a backup and a  Compressed Archive of
# the MySQL dump.
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
