#!/usr/bin/env bash
# A script that pings IP address passed as a parameter 5 times

if [ $# -ne 1 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit 1
fi

# Retrieve the IP address from CMD args
ip_address="$1"

ping -c 5 "$ip_address"
