#!/usr/bin/env bash
# Bug: sudo nginx status returns 'not running'
# Solution: https://stackoverflow.com/questions/16021481/nginx-not-listening-to-port-80

sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
sudo service nginx status | grep -q "not running" && echo " * nginx is not running"
