#!/usr/bin/env bash
# the FizzBuzz - prints number 1 - 100, outputs "Fizz" for multiples of 3 and
# Outputs "Buzz" for multiples of 5, and outputs "FizzBuzz" for multiples of 3 and 5 aswell

for ((i=1; i < 101; i++))
do
	if((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	elif ((i % 15 == 0)); then
		echo "FizzBuzz"
	else
		echo "$i"
	fi
done
