#!/usr/bin/env bash
# This script displays "Best School" 10 times and says "Hi" on the 9th itteration

i=1
while [ "$i" -le 10 ]
do
	echo "Best School"
	if [ "$i" -eq 9 ]; then
		esho "Hi"
	fi
	(( i++ ))
done
