#!/usr/bin/env bash
# This script gives you information about a "school" file
# ( if it exist, empty, not empty, regular or not regular"

file="school"

if [ -e $"file" ]; then
	echo "$file file exists"

	if [ -s $file" ]; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi

	if [ -f "$file" ]; then
		echo "$file is a ragular file"
	fi
else
	echo "$file file does not exist"
fi
