#!/usr/bin/env bash
# Fix container to run as nginx user & listen on all active IPs on port 8080

# Update nginx config file with user 'nginx'
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# Change ownership and permissions of config file
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf

# Update nginx file to listen on 8080
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# netstat -lpn shows apache2 is using 8080
pkill apache2
sudo -u nginx service nginx restart
